### ISSUE TITLE
Support profile embedding

### ISSUE THREAD

**Issue by dalkommatt** [vercel/react-tweet#105]
ex.

```<TwitterProfile profileUrl="https://twitter.com/vercel" showTweets={3} />```

**Comment by steven-tey** [comment]
Unfortunately this would require Twitter API v2 + we want to keep this library as simple as possible so it won't be added 😅 

Closing this for now, but appreciate the feature request!

**Comment by dalkommatt** [comment]
@steven-tey are you sure? Profile/timeline embedding is [supported by Twitter ](https://publish.twitter.com/?query=https%3A%2F%2Ftwitter.com%2Fvercel&widget=Timeline) 

```<a class="twitter-timeline" href="https://twitter.com/vercel?ref_src=twsrc%5Etfw">Tweets by vercel</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>```
