### ISSUE TITLE
Browser tracking prevention seems to break media preview

### ISSUE THREAD

**Issue by mrhoodz** [vercel/react-tweet#108]
It looks like if tracking prevention is turned on, images and videos do not load.

**Comment by steven-tey** [comment]
Can you outline some steps to reproduce this? I tried doing it in Safari but it didn't break the media preview

**Comment by mrhoodz** [comment]
Ok so l dug a bit deeper. Turns out this only happens on edge browser.
![image](https://github.com/vercel/react-tweet/assets/55862003/a77768cf-05d4-4e80-ae15-7a7becd39144)

![image](https://github.com/vercel/react-tweet/assets/55862003/2dca9666-bcd4-4696-8b71-c623cd146597)

**Comment by mrhoodz** [comment]
[dub.sh](https://dub.sh/) somehow found a work around this.

**Comment by lfades** [comment]
@mrhoodz Does this also happen for normal Twitter embeds in https://publish.twitter.com/? in the case of dub.sh all images are relative paths under `/_next/image` but that's not the default for `react-tweet`

**Comment by mrhoodz** [comment]
@lfades The normal twitter embeds work just fine. Interesting to note is that if you try to open the image url from the **_pbs.twing.com_** in a new tab it loads the image as expected. 

I’m curious if the bub.sh team chose to use an image url different from the one that is return by the tweeter api, maybe they also bumbed into this issue 🤷‍♂️

**Comment by lfades** [comment]
dub.sh uses a different theme and not the default Twitter theme (completely different components that use next/image for the author image.)

It would be interesting to know why are the images being blocked though, I can't reproduce it in my chrome.

**Comment by mrhoodz** [comment]
**Update**

I uninstalled all my browsers and reinstalled them. The problem seems to be gone (weird behaviour coz l was already on the latest versions anyway).

 I wish l had a more helpful info on how to fix the problem but l think it's safe to say this was an issue with my PC l hope not too many people bump into this problem.

 I'm closing the issue now thank you 🙏.
