### ISSUE TITLE
New Twitter Logo

### ISSUE THREAD

**Issue by MikeKratzmann** [vercel/react-tweet#109]
Hey folks, the Twitter logo changed from the Bird to an X.
Could you please change it?

**Comment by leerob** [comment]
Enter: https://react-xeet.vercel.app/

**Comment by MikeKratzmann** [comment]
> Enter: https://react-xeet.vercel.app/

> It's also a parody and should not be used too seriously.

**Comment by MikeKratzmann** [comment]
i would really appreciate to get this change in this repo here.
