### ISSUE TITLE
Adding several tweets (tens) in a single page 

### ISSUE THREAD

**Issue by MohammedAlrozzi** [vercel/react-tweet#114]
Are there a way to create static tweets in a single page by making a reference to the tweets ID. I need to do that so that I can close my twitter account while keeping my library of tweets and bookmarks. Thanks a lot.

**Comment by lfades** [comment]
By making multiple calls to the same endpoint. So do a `promise.all` for all your tweets that calls [`getTweet`](https://react-tweet.vercel.app/api-reference#gettweet).

If closing your account means your tweets won't be public anymore then I recommend you save your tweet's content into a local JSON file and use the [`EmbeddedTweet`](https://react-tweet.vercel.app/twitter-theme/api-reference#embeddedtweet) component to render it. If you go this route do note that any changes to the data returned by the tweet won't be applied to your local copy.
