### ISSUE TITLE
Can I get the full thread using getTweet?

### ISSUE THREAD

**Issue by trindadematheus** [vercel/react-tweet#124]
The API returns the tweet parent but I need at least the child's id

![image](https://github.com/vercel/react-tweet/assets/31348285/53551333-057d-4cb0-b28e-100d8a0dae84)

**Comment by lfades** [comment]
No, it's not possible to get the full thread. You would need to use [Twitter's API](https://developer.twitter.com/en/docs/twitter-api) if you need the entire thread.
