### ISSUE TITLE
Feedback for “API Reference”

### ISSUE THREAD

**Issue by bullishgopher** [vercel/react-tweet#164]
I won't use it since it's not fully customizable. What? if I want to show a tweet like below:

<img width="328" alt="image" src="https://github.com/vercel/react-tweet/assets/49041460/82fc05b8-9269-4810-bc64-26dcad45b704">

**Comment by tywayne** [comment]
You'll want to take a look at this section of the docs - https://react-tweet.vercel.app/twitter-theme/advanced

There are customization options for the provided components, but the library exposes approaches for building a fully custom tweet display.

**Comment by bullishgopher** [comment]
> You'll want to take a look at this section of the docs - https://react-tweet.vercel.app/twitter-theme/advanced
> 
> There are customization options for the provided components, but the library exposes approaches for building a fully custom tweet display.

That's looks great. It works like a charm 😇

**Comment by bullishgopher** [comment]
@tywayne btw, is there any way to change the font size?
