### ISSUE TITLE
Incorrect avatar is used for Twitter voice posts

### ISSUE THREAD

**Issue by karol-majewski** [vercel/react-tweet#165]
Hello and thank you for your work.

I noticed that when a tweet containing a [voice post](https://help.twitter.com/en/using-x/voice-post) [such as this one](https://twitter.com/metaLulie/status/1530484733985038337) is used, the avatar displayed in the embed does not match the author of the post.

If you open it on X, it looks like this (correct):

![CleanShot 2024-04-11 at 11 21 35@2x](https://github.com/vercel/react-tweet/assets/20233319/b6b4ee8a-c0b3-48aa-abec-6b6e64534140)

But if you open it [inside the demo](https://react-tweet-next.vercel.app/light/1530484733985038337), then it looks like that (incorrect):

![CleanShot 2024-04-11 at 11 21 26@2x](https://github.com/vercel/react-tweet/assets/20233319/abe610cb-6fec-415f-b3cb-81850939b0de)

**Comment by lfades** [comment]
Note that we don't match react-tweet to X's website but to X's own embedded tweet. So in that case it would be: https://publish.twitter.com/?query=https://twitter.com/metaLulie/status/1530484733985038337&widget=Tweet

**Comment by karol-majewski** [comment]
Ah, my mistake! I should have checked the official embed first instead of assuming the issue was somewhere else. I stand corrected ;)
